spring.application.name=config-server
server.port=${CONFIG_SERVER_PORT:8888}

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:${CONFIG_REPO_PATH:./config-repo}

management.endpoints.web.exposure.include=health,info
